version: "3"

services: 
  valheim:
    build:
      context: .
      dockerfile: dockerfile      
    image: valheim-server-docker:0.0.1
    cap_add:
      - sys_nice
    volumes: 
      - /data/valheim/config:/config
      - /data/valheim/data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
    env_file:
      - /data/valheim/valheim.env
    restart: always
    stop_grace_period: 2m
