version: "3"

services: 
  valheim:
    build:
      context: .
      dockerfile: Dockerfile      
    image: valheim-server-docker:0.0.2
    cap_add:
      - sys_nice
    volumes: 
      - /data/valheim/config:/config
      - /data/valheim/data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
    environment:
      SERVER_NAME: ${SERVER_NAME}
      SERVER_PASS: ${SERVER_PASS}
      WORLD_NAME: ${WORLD_NAME}
      SERVER_PUBLIC: ${SERVER_PUBLIC}
      TZ: ${TZ}
      VALHEIM_PLUS: ${VALHEIM_PLUS}
      SUPERVISOR_HTTP: ${SUPERVISOR_HTTP}
      SUPERVISOR_HTTP_USER: ${SUPERVISOR_HTTP_USER}
      SUPERVISOR_HTTP_PASS: ${SUPERVISOR_HTTP_PASS}
      STATUS_HTTP: ${STATUS_HTTP}
      DISCORD_WEBHOOK: ${DISCORD_WEBHOOK}
      DISCORD_POST_SERVER_RUN: ${DISCORD_POST_SERVER_RUN}
      POST_SERVER_RUN_HOOK: ${POST_SERVER_RUN_HOOK}
      DEBIAN_FRONTEND: ${DEBIAN_FRONTEND}
    restart: always
    stop_grace_period: 2m
