<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\VDS.Contracts\VDS.Contracts.csproj" />
    <ProjectReference Include="..\VDS.Core\VDS.Core.csproj" />
    <ProjectReference Include="..\VDS.Infrastructure\VDS.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
